# Workflow to build main.tex into main.pdf, using repository_dispatch trigger
name: build
on:
  push:
    branches: [main, master]

jobs:
  build-cv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install TeX deps, setup uv, and build via Makefile
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            make curl python3 python3-venv \
            latexmk biber texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
          uv --version
          uv sync
          make pdf

      - name: Commit results
        if: ${{ github.actor != 'nektos/act' }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add -f main.pdf || echo "No changes to add"
          git commit -m 'Re-build CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Repository Dispatch
        if: ${{ github.actor != 'nektos/act' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mikecuoco/michaelcuoco.com
          event-type: build-cv
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'