# Workflow to build main.tex into main.pdf, using repository_dispatch trigger
name: build
on:
  push:
    branches: [main, master]
  repository_dispatch:
    types: [get-commit-bibs]
    
jobs:
  build-cv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}

      - name: Get bibliographic data, install dependencies, build CV
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add wget
            wget https://raw.githubusercontent.com/mikecuoco/FindMyPubs/master/pubmed.bib
            wget https://raw.githubusercontent.com/mikecuoco/FindMyPubs/master/preprints.bib
            tlmgr update --self --all
            tlmgr install fontawesome5 paracol
            pdflatex main
            biber main
            pdflatex main

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add -f main.pdf || echo "No changes to add"
          git commit -m 'Re-build CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mikecuoco/michaelcuoco.com
          event-type: build-cv
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'